package cn.drcomo.redis;

import cn.drcomo.corelib.util.DebugUtil;
import org.bukkit.plugin.java.JavaPlugin;

import java.io.File;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 * Redis server-id 解析器
 *
 * 规则：
 * 1) 若配置填写了 server-id，优先使用
 * 2) 若未填写，则根据当前插件 JAR 绝对路径自动生成
 * 3) 若发生冲突（同 id 被其他实例占用），追加短哈希重试
 */
public class RedisServerIdResolver {

    private final JavaPlugin plugin;
    private final DebugUtil logger;

    public RedisServerIdResolver(JavaPlugin plugin, DebugUtil logger) {
        this.plugin = plugin;
        this.logger = logger;
    }

    public ResolvedServerIdentity resolve(
            RedisConnection redis,
            String configuredServerId,
            String configuredOwner,
            int claimTtlSeconds
    ) {
        String owner = normalizeOrEmpty(configuredOwner);
        if (owner.isEmpty()) {
            owner = buildOwnerFromRuntime();
        }

        String baseId = normalizeOrEmpty(configuredServerId);
        boolean autoGenerated = false;
        if (baseId.isEmpty()) {
            baseId = buildServerIdFromJarPath();
            autoGenerated = true;
        }

        // Redis 不可用时返回解析结果，不做占用校验
        if (redis == null || !redis.isReady()) {
            return new ResolvedServerIdentity(baseId, owner, autoGenerated, false);
        }

        String candidate = baseId;
        int maxAttempts = 6;
        for (int i = 0; i < maxAttempts; i++) {
            if (redis.tryClaimServerId(candidate, owner, claimTtlSeconds)) {
                if (i > 0) {
                    logger.warn("Redis server-id 发生冲突，已自动切换为: " + candidate);
                }
                return new ResolvedServerIdentity(candidate, owner, autoGenerated, true);
            }

            String occupiedBy = redis.getServerIdOwner(candidate);
            if (owner.equals(occupiedBy)) {
                // 同 owner 视为可复用（例如重启窗口）
                boolean refreshed = redis.refreshServerIdClaim(candidate, owner, claimTtlSeconds);
                if (refreshed) {
                    return new ResolvedServerIdentity(candidate, owner, autoGenerated, true);
                }
            }

            // 发生冲突，生成新候选
            candidate = baseId + "-" + shortHash(owner + "#" + i);
        }

        // 兜底：即便未占用成功，也返回最后候选并标记未 claim
        logger.warn("Redis server-id 自动占用失败，可能存在并发冲突: " + candidate);
        return new ResolvedServerIdentity(candidate, owner, autoGenerated, false);
    }

    private String buildServerIdFromJarPath() {
        try {
            File jar = resolveRuntimeArtifactFile();
            File parent = jar.getParentFile();
            String parentName = parent != null ? sanitize(parent.getName()) : "plugins";
            String jarName = sanitize(stripExt(jar.getName()));
            String pathHash = shortHash(jar.getAbsolutePath().toLowerCase());

            String id = "auto-" + parentName + "-" + jarName + "-" + pathHash;
            return limit(id, 96);
        } catch (Exception e) {
            return "auto-drcomovex-" + shortHash(String.valueOf(System.nanoTime()));
        }
    }

    private String buildOwnerFromRuntime() {
        String jarPath;
        try {
            jarPath = resolveRuntimeArtifactFile().getAbsolutePath();
        } catch (Exception e) {
            jarPath = plugin.getName();
        }

        long pid = -1L;
        try {
            pid = ProcessHandle.current().pid();
        } catch (Throwable ignored) {
        }

        String base = jarPath + "|" + pid;
        return "owner-" + shortHash(base.toLowerCase());
    }

    private String stripExt(String name) {
        int idx = name.lastIndexOf('.');
        return idx > 0 ? name.substring(0, idx) : name;
    }

    private String sanitize(String raw) {
        if (raw == null || raw.isEmpty()) {
            return "unknown";
        }
        String s = raw.replaceAll("[^a-zA-Z0-9._-]", "-")
                .replaceAll("-+", "-")
                .toLowerCase();
        if (s.startsWith("-")) {
            s = s.substring(1);
        }
        if (s.endsWith("-")) {
            s = s.substring(0, s.length() - 1);
        }
        return s.isEmpty() ? "unknown" : s;
    }

    private String normalizeOrEmpty(String v) {
        return v == null ? "" : v.trim();
    }

    private String limit(String s, int max) {
        if (s == null) {
            return "";
        }
        return s.length() <= max ? s : s.substring(0, max);
    }

    private String shortHash(String text) {
        try {
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] digest = md.digest(text.getBytes(StandardCharsets.UTF_8));
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < 5 && i < digest.length; i++) {
                sb.append(String.format("%02x", digest[i]));
            }
            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            return Integer.toHexString(text.hashCode());
        }
    }

    private File resolveRuntimeArtifactFile() {
        try {
            URL location = plugin.getClass().getProtectionDomain().getCodeSource().getLocation();
            if (location != null) {
                return new File(location.toURI()).getAbsoluteFile();
            }
        } catch (Exception ignored) {
        }

        // 回退：使用插件数据目录的绝对路径
        return plugin.getDataFolder().getAbsoluteFile();
    }

    public static class ResolvedServerIdentity {
        private final String serverId;
        private final String owner;
        private final boolean autoGenerated;
        private final boolean claimed;

        public ResolvedServerIdentity(String serverId, String owner, boolean autoGenerated, boolean claimed) {
            this.serverId = serverId;
            this.owner = owner;
            this.autoGenerated = autoGenerated;
            this.claimed = claimed;
        }

        public String getServerId() {
            return serverId;
        }

        public String getOwner() {
            return owner;
        }

        public boolean isAutoGenerated() {
            return autoGenerated;
        }

        public boolean isClaimed() {
            return claimed;
        }
    }
}
