# ================================================================
# DrcomoVEX - 基于直觉设计的服务器变量管理系统
# 版本: 1.0.0 (代号: 直觉)
# 作者: BaiMo
# ================================================================

# 数据库配置
database:
  # 数据库类型: sqlite 或 mysql
  type: "sqlite"
  
  # SQLite 配置
  file: "drcomovex.db"
  
  # MySQL 配置
  mysql:
    host: "localhost"
    port: 3306
    database: "drcomovex"
    username: "root"
    password: "password"
    useSSL: false
  
  # 连接池配置 (已根据性能分析报告优化)
  pool:
    minimum-idle: 5              # 增加最小空闲连接，提升基础性能
    maximum-pool-size: 20        # 增加最大连接数，适应高并发场景
    connection-timeout: 30000    # 30秒连接超时
    idle-timeout: 600000         # 10分钟空闲超时
    max-lifetime: 1800000        # 30分钟最大生命周期

# 数据保存配置
data:
  # 是否启用自动保存
  auto-save: true
  
  # 保存间隔（分钟）
  save-interval-minutes: 5
  
  # 玩家退出时是否保存数据
  save-on-player-quit: true

# 周期性重置配置
cycle:
  # 是否启用周期性重置
  enabled: true
  
  # 检查间隔（分钟）
  check-interval-minutes: 1
  
  # 时区设置
  timezone: "Asia/Shanghai"

# 基本设置
settings:
  # 是否检查更新
  check-updates: true
  
  # 是否通知OP更新
  notify-ops: true

# 调试配置
debug:
  # 日志级别: DEBUG, INFO, WARN, ERROR
  level: "INFO"