# ================================================================
# DrcomoVEX - 基于直觉设计的服务器变量管理系统
# 版本: 1.0.0 (代号: 直觉)
# 作者: BaiMo
# ================================================================

# 数据库配置
database:
  # 数据库类型: sqlite 或 mysql
  type: "sqlite"
  
  # SQLite 配置
  file: "drcomovex.db"
  
  # MySQL 配置
  mysql:
    host: "localhost"
    port: 3306
    database: "drcomovex"
    username: "root"
    password: "password"
    useSSL: false
  
  # 连接池配置 (已根据性能分析报告优化)
  pool:
    minimum-idle: 5              # 增加最小空闲连接，提升基础性能
    maximum-pool-size: 20        # 增加最大连接数，适应高并发场景
    connection-timeout: 30000    # 30秒连接超时
    idle-timeout: 600000         # 10分钟空闲超时
    max-lifetime: 1800000        # 30分钟最大生命周期

# 缓存配置
cache:
  # 是否启用缓存
  enabled: true
  
  # 缓存过期时间（分钟）
  expire-minutes: 10
  
  # 最大缓存数量
  maximum-size: 10000
  
  # 解析缓存配置
  parse-cache:
    enabled: true
    expire-minutes: 5
    maximum-size: 5000

# 数据保存配置
data:
  # 是否启用自动保存
  auto-save: true
  
  # 保存间隔（分钟）
  save-interval-minutes: 5
  
  # 玩家退出时是否保存数据
  save-on-player-quit: true

# 周期性重置配置
cycle:
  # 是否启用周期性重置
  enabled: true
  
  # 检查间隔（分钟）
  check-interval-minutes: 1
  
  # 时区设置
  timezone: "Asia/Shanghai"

# 基本设置
settings:
  # 是否检查更新
  check-updates: true
  
  # 是否通知OP更新
  notify-ops: true

# 调试配置
debug:
  # 日志级别: DEBUG, INFO, WARN, ERROR
  level: "INFO"
  
  # 是否将日志输出到文件
  log-to-file: false
  
  # 是否记录SQL语句
  log-sql: false

# 安全配置
security:
  # 最大递归深度
  max-recursion-depth: 10
  
  # 最大表达式长度
  max-expression-length: 1000
  
  # 是否允许循环引用
  allow-circular-references: false

# 性能配置 (已根据性能分析报告全面优化)
performance:
  # 异步线程池大小
  async-pool-size: 4
  
  # 是否启用性能监控
  enable-metrics: true
  
  # 内存优先存储配置
  memory-storage:
    # 启用内存优先存储
    enabled: true
    # 最大内存使用量 (MB) - 根据服务器内存调整
    max-memory-mb: 512
    # 玩家数据过期时间（分钟，玩家离线后）
    player-data-expire-minutes: 30
    # 内存清理阈值 (%) - 适当提高清理阈值
    cleanup-threshold: 85
    # 紧急清理阈值 (%)
    emergency-cleanup-threshold: 95
  
  # 批量持久化配置
  batch-persistence:
    # 批量持久化间隔（秒） - 更频繁的持久化
    batch-interval-seconds: 15
    # 最大批次大小 - 增加批次大小
    max-batch-size: 2000
    # 内存压力阈值触发持久化 (%)
    memory-pressure-threshold: 80.0
    # 最大重试次数
    max-retries: 3
  
  # 异步队列配置
  async-queue:
    # 异步写入队列大小
    queue-size: 10000
    # 工作线程数
    worker-threads: 2
  
  # 三级缓存系统配置
  cache:
    l2-expression-cache:
      # 延长表达式缓存时间，减少重复解析
      expire-minutes: 10
      # 增加缓存容量，提升命中率
      maximum-size: 20000
    l3-result-cache:
      # 延长结果缓存时间
      expire-minutes: 5
      # 增加结果缓存容量
      maximum-size: 10000

# 未来扩展配置
features:
  # 启用实验性功能
  experimental-features: false
  
  # 支持的扩展模块
  enabled-modules:
    - "core"
    - "variables"
    - "database"
    - "cache"
    - "cycle"
    - "placeholders"