# ================================================================
# DrcomoVEX - 变量定义文件
# 这里定义了所有的服务器变量和玩家变量
# 
# 支持的类型: INT, DOUBLE, STRING, LIST
# 支持的作用域: player, global
# 支持的周期: DAILY, WEEKLY, MONTHLY, YEARLY, Cron表达式
# ================================================================

variables:
  
  # ======================== 玩家变量示例 ========================
  
  # 玩家金币 - 数值类型，有约束
  player_money:
    name: "玩家金币"
    scope: "player"
    type: "DOUBLE"
    initial: 100.0
    min: 0
    max: 999999.99
  
  # 玩家等级 - 整数类型
  player_level:
    name: "玩家等级"
    scope: "player"
    type: "INT"
    initial: 1
    min: 1
    max: 100
  
  # 玩家经验值 - 整数类型，无上限
  player_exp:
    name: "玩家经验值"
    scope: "player"
    type: "INT"
    initial: 0
    min: 0
  
  # 玩家称号列表 - 列表类型
  player_titles:
    name: "玩家称号"
    scope: "player"
    type: "LIST"
    initial:
      - "新手冒险家"
    max: 10
  
  # 玩家状态 - 字符串类型
  player_status:
    name: "玩家状态"
    scope: "player"
    type: "STRING"
    initial: "正常"
  
  # ======================== 周期性变量示例 ========================
  
  # 每日登入奖励领取状态 - 每日重置
  daily_reward_claimed:
    name: "每日奖励领取状态"
    scope: "player"
    type: "STRING"
    initial: "false"
    cycle: "DAILY"
  
  # 每日任务进度 - 每日重置
  daily_task_progress:
    name: "每日任务进度"
    scope: "player"
    type: "INT"
    initial: 0
    min: 0
    max: 100
    cycle: "DAILY"
  
  # 周排行榜积分 - 每周重置
  weekly_score:
    name: "周排行榜积分"
    scope: "player"
    type: "INT"
    initial: 0
    min: 0
    cycle: "WEEKLY"
  
  # 月度活跃度 - 每月重置
  monthly_activity:
    name: "月度活跃度"
    scope: "player"
    type: "INT"
    initial: 0
    min: 0
    cycle: "MONTHLY"
  
  # ======================== 动态变量示例 ========================
  
  # 玩家战斗力 - 根据等级和金币计算
  player_combat_power:
    name: "玩家战斗力"
    scope: "player"
    type: "DOUBLE"
    initial: "(${player_level} * 10) + (${player_money} / 100)"
    min: 0
  
  # 玩家综合评分 - 复杂计算
  player_overall_score:
    name: "玩家综合评分"
    scope: "player"
    type: "DOUBLE"
    initial: "${player_level} * 0.3 + ${player_exp} * 0.0001 + ${player_money} * 0.01"
    min: 0
  
  # VIP等级显示 - 使用PlaceholderAPI
  player_vip_display:
    name: "VIP等级显示"
    scope: "player"
    type: "STRING"
    initial: "%vault_prefix% %player_name%"
  
  # ======================== 服务器全局变量示例 ========================
  
  # 服务器公告 - 全局字符串
  server_motd:
    name: "服务器公告"
    scope: "global"
    type: "STRING"
    initial: "欢迎来到我们的服务器！"
  
  # 服务器状态 - 全局数值
  server_status:
    name: "服务器状态"
    scope: "global"
    type: "INT"
    initial: 1
    min: 0
    max: 2
  
  # 全服在线人数 - 动态获取
  server_online_count:
    name: "全服在线人数"
    scope: "global"
    type: "INT"
    initial: "%server_online%"
    min: 0
  
  # 服务器TPS - 动态获取
  server_tps:
    name: "服务器TPS"
    scope: "global"
    type: "DOUBLE"
    initial: "%server_tps%"
    min: 0
    max: 20
  
  # ======================== 高级功能示例 ========================
  
  # 动态金币上限 - 根据等级动态调整
  player_money_cap:
    name: "玩家金币上限"
    scope: "player"
    type: "DOUBLE"
    initial: "1000 + ${player_level} * 500"
    min: 1000
  
  # 每日登入奖励金额 - 动态计算
  daily_login_bonus:
    name: "每日登入奖励"
    scope: "player"
    type: "DOUBLE"
    initial: "50 + ${player_level} * 10"
    min: 50
    cycle: "DAILY"
  
  # 复合周期变量 - 每天中午0点重置
  complex_daily_reset:
    name: "复合每日重置"
    scope: "player"
    type: "INT"
    initial: 0
    cycle: "0 0 0 * * ?"  # Cron表达式: 每日凌敨0点
  
  # ======================== 限制条件示例 ========================
  
  # 只读变量 - 不能修改
  readonly_server_version:
    name: "服务器版本"
    scope: "global"
    type: "STRING"
    initial: "%server_version%"
    limitations:
      read-only: true
  
  # 不持久化变量 - 不保存到数据库
  temp_session_data:
    name: "临时会话数据"
    scope: "player"
    type: "STRING"
    initial: ""
    limitations:
      persistable: false

  # 安全限制变量 - 限制表达式复杂度
  secure_calculation:
    name: "安全计算"
    scope: "player"
    type: "DOUBLE"
    initial: "${player_level} + ${player_exp}"
    limitations:
